### ISSUE TITLE
Contents of storage does not printed in standalone inverted_index

### ISSUE THREAD

**Issue by rimms** [jubatus/jubadump#22]
https://github.com/jubatus/jubadump/blob/0.8.0/src/jubatus/dump/recommender.cpp#L62

I think we should dump `storage.inv_diff_`.

**Comment by kmaehashi** [comment]
Discussion in the meeting:
* We should consider if just adding the diff area to output is sufficient; [weight_manager](https://github.com/jubatus/jubadump/blob/0.8.0/src/jubatus/dump/weight_manager.cpp) merge diff/master area before printing it.
